export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const TRAVELER_SIGNOUT = 'TRAVELER_SIGNOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SET_ACTIVE_JOB = 'SET_ACTIVE_JOB';
export const SET_CURRENT_CONVERSATION = 'SET_CURRENT_CONVERSATION';

export const GET_PROFILE_PIC = 'GET_PROFILE_PIC';
export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';
export const GET_RESUME = 'GET_RESUME';
export const SUBMIT_RESUME = 'SUBMIT_RESUME';
export const SUMIT_PROFILE_PIC = 'SUMIT_PROFILE_PIC';
export const SUBMIT_PERSONAL_PROFILE = 'SUBMIT_PERSONAL_PROFILE';
export const SUBMIT_EDUCATION_DETAILS = 'SUBMIT_EDUCATION_DETAILS';
export const SUBMIT_EXPERIENCE_DETAILS = 'SUBMIT_EXPERIENCE_DETAILS';
export const SUMIT_SKILLS_DETAILS = 'SUMIT_SKILLS_DETAILS';





export const SET_SEARCH_USER='SET_SEARCH_USER';
