export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const TRAVELER_SIGNOUT = 'TRAVELER_SIGNOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SET_ACTIVE_JOB = 'SET_ACTIVE_JOB';
export const SET_CURRENT_CONVERSATION = 'SET_CURRENT_CONVERSATION';